### ISSUE TITLE
Coordinator Volume setzen geht nicht mehr richtig

### ISSUE THREAD

**Issue by Stormbringer11** [ioBroker/ioBroker.sonos#149]
Hallo,

wollte gerade einen Taster zur Volumensteuerung installieren dabei ist mir folgender Bug aufgefallen:

Wenn der Coordinator in der Gruppe ist, wird einfach ein ganz anderer Wert umgesetzt. Selbst wenn man es bei den Objekten direkt eingibt wird aus einem "8" z. B. ein "11". Bei den anderen Player der Gruppe funktioniert es nach wie vor einwandfrei.
Wenn man den Coordinator alleine (ohne andere Player) betreibt funktioniert das Volumen setzen auch wie erwartet. Kann nur leider nicht sagen seit wann das Problem besteht. Im Log taucht nichts verdächtiges auf, er ändert den Wert einfach.

Sonos Adapter Version: 2.1.7
Admin 5.3.1
JS-Controller 4.0.21
Node.js 14.19.0
npm 6.14.16

Wäre nett, wenn ihr euch das mal anschauen könntet.

**Comment by mifrit00** [comment]
Ich habe das gleiche Problem und würde mich auch über einen Fix freuen.

**Comment by Orti85** [comment]
Ich kann das Problem auch nur bestätigen.
Jedoch konnte ich es noch in soweit eingrenzen, dass das setzten der einzel Volumen sowie group Volumen funktioniert.
Beim Feedback der Master players wird nur leider die Rückmeldung des Group Volumen auch als einzel Volumen des Master players übernommen womit die Anzeige des Istwertes sich nicht mit der Realität deckt.
Nach zu vollziehen indem man die Werte parallel in der Sonos App verfolgt.

Vielleicht kann sich dies einmal ein developer anschauen.
Sonst kann ich nur sagen danke für das geile Plugin.

Gruß Orti

**Comment by Rello** [comment]
+1 on this one.

The coordinator level.volume is always set the same as the level.volume.group

The resulting problem is, that when you have different speakers in a group, the group volume is a calculated average and does not reflect the current coordinator level.volume

In my case I want to set the group members to a factored lower value than the coordinator due to placing. but this does not work with the current issue

thank you

**Comment by Rello** [comment]
I think the problem is this section:

https://github.com/ioBroker/ioBroker.sonos/blob/master/main.js#L1646-L1673

following logs:

- set one member volume via app to 35: `volume: Volume for http://192.168.0.25:1400: 35`
- with 2 sec delay, this sets the group volume as calculated by sonos: `group_volume: groupVolume for http://192.168.0.25:1400: 26` (https://github.com/ioBroker/ioBroker.sonos/blob/master/main.js#L1734)

this would be all good then. but unfortulately , this trigger overwites the displayed Volume wrongly 
`group-volume: Volume for http://192.168.0.25:1400: 26`
https://github.com/ioBroker/ioBroker.sonos/blob/master/main.js#L1646

so the last trigger messes everything up and should be removed in my opinion

**Comment by gaga191281** [comment]
+1. A really annoying bug. This makes the adapter nearly unusable when used with groups. Because of unexpected volume changes of the coordinator when volume changed from another room.

**Comment by Apollon77** [comment]
Ok, the question is now why this code is in :-) I think the assumption is that the group volume will be adjusted as soon as you set the volume for one group member ... If this is not that way I can remove these lines ...

**Comment by Rello** [comment]
thats a good question. perhaps from earlier, where these values were updated in 2 updates and now all is coming in one?
no clue.
but as tested, I thinks its obsolet. Just give it a try and in worst case, revert it

**Comment by gaga191281** [comment]
The datapoint groupVolume is to change the volume of the whole group, isn‘t it?

**Comment by Apollon77** [comment]
Then you are welcome to check the GitHub version! (version number will not change, GitHub installs can take 10+mins with npm6 currently ... stay patience). Please tell if anything still work

**Comment by gaga191281** [comment]
Will try it next week. I am out of town over the holidays.

**Comment by Apollon77** [comment]
Ok, will aeaitz until release, or @Rello, @mifrit00 , @Stormbringer11  maybe available for a check with GitHub version?

**Comment by Rello** [comment]
Hello,
Any how to on testing a github version?
Still new on IO

**Comment by Apollon77** [comment]
If you have admin v5 then: enable expert mode, a new icon appears with a github symbol "Custom install", use the "from github "tab there and select adapter.

If you already uise admin v6 then there is a bug currently - use the "from URL" in the custom install dialog and enter https://github.com/ioBroker/ioBroker.sonos as URL

GitHub installs can take 10ü+ mins with npm6 right nwo ... just wait for it to be done

**Comment by Rello** [comment]
Thank you. Download worked. Will verify this evening

**Comment by Rello** [comment]
Hello,

your suggestion seems to be correct also here. from the log:
```
volume: Volume for http://192.168.0.25:1400: 20
volume: Volume for http://192.168.0.24:1400: 10
group-volume: Volume for http://192.168.0.25:1400: 15
```

this also suggests, that the group volume (15, which is correct) is overwritten to the "volume" in the line 1682 mentioned above.
I would also suggest to change it to
adapter.setState({device: 'root', channel: ip, state: '**group_volume**'}, {val: data.newVolume, ack: true});

**Comment by Apollon77** [comment]
Ok, thank you, I did the same change now on GitHub ... please check that again

**Comment by gaga191281** [comment]
@Rello strange. Works for me. `group-volume` is changed, but only for the coordinator. To be honest, I don't know if this is expected or if the value of each group member should be changed.
Regarding your error message, I don't get this message.
